using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Lunaria.Proto.Analyzers;

[Generator]
public sealed class TrackedPropertyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var properties = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Lunaria.Common.Tracking.TrackedAttribute",
            static (node, _) => node is PropertyDeclarationSyntax,
            static (ctx, _) => (IPropertySymbol)ctx.TargetSymbol).Collect();
        context.RegisterSourceOutput(properties, Emit);
        var roots = context.SyntaxProvider.ForAttributeWithMetadataName("Lunaria.Common.Tracking.TrackChildrenAttribute",
            static (node, _) => node is ClassDeclarationSyntax, static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);
        context.RegisterSourceOutput(roots, static (ctx, type) => {
            var text = new StringBuilder("// <auto-generated/>\n#nullable enable\nnamespace ")
                .Append(type.ContainingNamespace.ToDisplayString()).Append(";\npartial class ").Append(type.Name)
                .Append(" { private void ConnectTrackedChildren() {\n");
            foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
                if (!property.IsStatic && property.Type.AllInterfaces.Any(i => i.ToDisplayString() == "Lunaria.Common.Tracking.ITrackedState"))
                    text.Append("Observe(").Append(property.Name).Append(", nameof(").Append(property.Name).Append("));\n");
            ctx.AddSource(type.Name + ".Children.g.cs", text.Append("} }").ToString());
        });
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<IPropertySymbol> properties)
    {
        foreach (var group in properties.GroupBy(p => p.ContainingType, SymbolEqualityComparer.Default))
        {
            var type = (INamedTypeSymbol)group.Key!;
            var text = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
            text.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).Append(";\n");
            var parents = new System.Collections.Generic.Stack<INamedTypeSymbol>();
            for (var parent = type; parent is not null; parent = parent.ContainingType) parents.Push(parent);
            foreach (var parent in parents)
                text.Append("partial ").Append(parent.IsRecord ? "record " : "class ").Append(parent.Name).Append(" {\n");
            foreach (var property in group)
            {
                var syntax = (PropertyDeclarationSyntax)property.DeclaringSyntaxReferences[0].GetSyntax();
                var name = property.Name;
                var field = "__tracked" + name;
                text.Append(string.Join(" ", syntax.Modifiers.Select(m => m.Text))).Append(' ')
                    .Append(property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
                        SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier)))
                    .Append(' ').Append(name).Append(" {\n");
                foreach (var accessor in syntax.AccessorList!.Accessors)
                {
                    text.Append(string.Join(" ", accessor.Modifiers.Select(m => m.Text))).Append(' ').Append(accessor.Keyword.Text);
                    if (accessor.Keyword.Text == "get") text.Append(" => Observe(").Append(field).Append(", nameof(").Append(name).Append("));\n");
                    else text.Append(" => SetTracked(ref ").Append(field).Append(", value, nameof(").Append(name)
                        .Append("), () => ").Append(field).Append(");\n");
                }
                text.Append("}\n");
            }
            foreach (var _ in parents) text.Append("}\n");
            context.AddSource(type.ToDisplayString().Replace('.', '_') + ".Tracking.g.cs", SourceText.From(text.ToString(), Encoding.UTF8));
        }
    }
}
