// <auto-generated />
// Source: Global/GlobalSystem/DataManager/DataEnumTypeConfig.lua
// Regenerate: python tools/import_wanted_enums.py <path-to-DataEnumTypeConfig.lua>
namespace Lunaria.Game.Resources;

public enum EWantedAwardType : uint
{
    AddCoinTypeA = 1,
    AddCoinTypeB = 2,
    AddBlessSelect = 3,
    AddBlessRandom = 4,
    AddRelicSelect = 6,
    AddRelicRandom = 7,
    AddCreatureSelect = 9,
    AddOneCreature = 10,
    ChangeHP = 11,
}

public enum WantedPosterRandomRewardType : uint
{
    Bless = 1,
    Relic = 2,
    Creature = 3,
}

public enum BlessType : uint
{
    Blue = 1,
    Purple = 2,
    Gold = 3,
}
