syntax = "proto3";

package msg;
option  go_package = "proto/GameMsg";


enum EClientServerCmds
{
    CS_CMD_BEGIN = 0;

    CS_PING = 1;
    SC_PONG = 2;

    CS_REQ_GM         = 104; 
    CS_NOTIFY_GM_TEXT = 105; 

    SC_NOTIFY_UDP_INFO = 120; 

    CS_ACCOUNT_LOGIN   = 10001; 
    SC_ACCOUNT_LOGIN   = 10002; 
    CS_REQ_ROLE_LIST   = 10003; 
    CS_RES_ROLE_LIST   = 10004; 
    CS_CREATE_ROLE     = 10005; 
    SC_CREATE_ROLE     = 10006; 
    CS_ROLE_LOGIN      = 10007; 
    SC_ROLE_LOGIN      = 10008; 
    CS_REQ_ROLE_LOGOUT = 10011; 
    SC_ROLE_LOGOUT     = 10012; 
    CS_ENTER_MAP       = 10013; 
    SC_ENTER_MAP       = 10014; 
    CS_FIN_ENTER_MAP   = 10015; 
    SC_FIN_ENTER_MAP   = 10016; 
    SC_MAP_READY_NTF   = 10017; 
    CS_UDP_PING_PONG   = 10018; 
    SC_UDP_PING_PONG   = 10019; 
    CS_INIT_ROLE_GENDER_AND_NAME = 10020; 
    SC_INIT_ROLE_GENDER_AND_NAME = 10021; 
    CS_CHECK_TEXT = 10022; 
    SC_CHECK_TEXT = 10023; 
    CS_SCHEMA_INFO_SYNC = 10024; 
    SC_SCHEMA_INFO_SYNC = 10025; 
    SC_BAN_USER_NTF = 10026; 
    CS_ROLE_INFO_REQ = 10027; 
    SC_ROLE_INFO_RES = 10028; 




    CS_REPORT_TIME = 10051; 
    SC_REPORT_TIME = 10052;
    CS_QUERY_TIME  = 10053; 
    SC_QUERY_TIME  = 10054;


    CS_REQ_CHARACTER_LIST         = 10101; 
    SC_RES_CHARACTER_LIST         = 10102; 
    CS_REQ_CHARACTER_LEVEL_UP     = 10103; 
    SC_RES_CHARACTER_LEVEL_UP     = 10104; 
    CS_CHARACTER_LEVEL_BREAK     = 10105; 
    SC_CHARACTER_LEVEL_BREAK     = 10106; 
    SC_NTF_CHARACTER_NEWCOMER     = 10107; 
    CS_CHARACTER_UPDATE_TEAM      = 10108; 
    SC_CHARACTER_UPDATE_TEAM      = 10109;
    CS_CHARACTER_SWITCH_TEAM      = 10110; 
    SC_CHARACTER_SWITCH_TEAM      = 10111;
    CS_CHARACTER_SWITCH_MEMBER    = 10112; 
    SC_CHARACTER_SWITCH_MEMBER    = 10113;
    SC_NTF_CHARACTER_UPDATE       = 10114; 
    SC_TEMPORARY_LIQUID_POOL_NTF  = 10115; 
    SC_PLAYER_LEVEL_DATA_NTF      = 10117; 
    CS_CHANGE_WORLD_LEVEL         = 10118; 
    SC_CHANGE_WORLD_LEVEL         = 10119; 
    CS_CHARACTER_TEAMS            = 10120; 
    SC_CHARACTER_TEAMS            = 10121; 
    CS_CHARACTER_UPDATE_TEAM_NAME = 10122; 
    SC_CHARACTER_TEMP_TEAM_NTF    = 10123; 
    CS_CHARACTER_UPDATE_TMP_TEAM  = 10124; 
    SC_CHARACTER_UPDATE_TMP_TEAM  = 10125; 
    CS_CHARACTER_TMP_TEAM_QUERY  = 10126; 
    SC_CHARACTER_TMP_TEAM_QUERY  = 10127; 
    CS_CHARACTER_HEAL_REQ         = 10128; 
    SC_CHARACTER_HEAL_RES         = 10129; 
    CS_SWITCH_MAIN_CHARACTER      = 10130; 
    SC_SWITCH_MAIN_CHARACTER      = 10131; 


    CS_ITEM_GET_LIST          = 10200; 
    SC_ITEM_GET_LIST          = 10201;
    CS_ITEM_USE               = 10202; 
    SC_ITEM_USE               = 10203;
    SC_ITEM_CHANGE_NTF        = 10204; 
    SC_PLAYER_ATTR_UPDATE_NTF = 10205; 
    SC_PRECIOUS_AWARD_SHOW_NTF = 10206; 

    CS_ITEM_BAG_GET_LIST        = 10210;
    SC_ITEM_BAG_GET_LIST        = 10211;
    SC_ITEM_BAG_CHANGE_NTF      = 10212;
    CS_ITEM_USE_COUNT           = 10213;
    SC_ITEM_USE_COUNT           = 10214;
    SC_ITEM_CD_NTF              = 10215; 
    SC_ITEM_ADD_ERROR_NTF        = 10216;
    SC_AWARD_SHOW_NTF           = 10217;


    CS_REQ_TASK_LIST            = 10300;
    SC_RES_TASK_LIST            = 10301;
    SC_NTF_TASK_PROGRESS_UPDATE = 10302;
    CS_TASK_ACTION_UPDATE       = 10303;
    SC_TASK_ACTION_UPDATE       = 10304;
    CS_TASK_ONRECONNECT = 10305;
    SC_TASK_ONRECONNECT = 10306;


    CS_SHOP_GOODS   = 10400;
    SC_SHOP_GOODS   = 10401;
    CS_SHOP_BUY     = 10402;
    SC_SHOP_BUY     = 10403;
    SC_MONEY_UPDATE = 10404;


    CS_SKILL_BOOK_QUERY = 10500;
    SC_SKILL_BOOK_QUERY = 10501;
    SC_SKILL_UPDATE     = 10502;
    CS_TALENT_QUERY     = 10511;
    SC_TALENT_QUERY     = 10512;
    CS_TALENT_UNLOCK    = 10513;
    SC_TALENT_UNLOCK    = 10514;

    CS_BUFF_SYNC   = 10600; 
    SC_BUFF_SYNC   = 10601;
    SC_BUFF_ADD    = 10602; 
    SC_BUFF_DEL    = 10603; 
    SC_BUFF_UPDATE = 10604; 


    CS_CASE_DATA               = 10700; 
    SC_CASE_DATA               = 10701; 
    CS_CASE_CLUE_PUT           = 10702; 
    SC_CASE_CLUE_PUT           = 10703; 
    SC_CASE_RECEIVE_NTF        = 10704; 
    SC_CASE_NEW_CLUE_NTF       = 10705; 
    SC_CASE_NEW_EVIDENCE_NTF   = 10706; 
    CS_CASE_EVIDENCE_DECRYPTED = 10707; 
    SC_CASE_EVIDENCE_DECRYPTED = 10708; 


    CS_Do_Gacha_Req                = 10720; 
    SC_Gacha_Result                = 10721; 
    CS_Get_Pool_Info_Req           = 10722; 
    SC_Get_Pool_Info_Ack           = 10723;
    CS_Get_Accumulated_Rewards_Req = 10724; 
    SC_Gacha_Rewards_Result_Ack    = 10725; 


    CS_REQ_REDPOINT_LIST = 10740; 
    SC_RES_REDPOINT_LIST = 10741; 
    CS_REQ_REDPOINT_MARKREAD = 10742; 
    SC_RES_REDPOINT_MARKREAD = 10743; 


    CS_SAVEPOINT_UNLOCK = 20000;    
    SC_SAVEPOINT_UNLOCK = 20001;
    CS_LOCATION_SYNC = 20002;       
    CS_NPC_DIALOGUE = 20003;        
    CS_ENTITY_OPERATION = 20004;    
    CS_SAVEPOINT_SYNC = 20005;      
    SC_SAVEPOINT_SYNC = 20006;
    SC_GAMETIME_SLIP_NTF = 20007;   
    CS_EXPOSE_GET_MONSTER_LIST = 20008; 
    SC_EXPOSE_GET_MONSTER_LIST = 20009; 
    CS_REQ_UNLOCK_TELEPORT = 20010; 
    SC_RES_UNLOCK_TELEPORT = 20011; 
    CS_GAMETIME_SETUP_REQ = 20012; 
    SC_GAMETIME_SETUP_RES = 20013; 


    CS_COLLECTION_GET_LIST = 20100; 
    SC_COLLECTION_GET_LIST = 20101;
    CS_COLLECTION_OPERATE  = 20102; 
    SC_COLLECTION_OPERATE  = 20103;
    SC_COLLECTION_DATA_NTF = 20104; 


    CS_MOTIVE_EQUIP = 20150; 
    SC_MOTIVE_EQUIP = 20151;
    CS_MOTIVE_LEVEUP = 20152; 
    SC_MOTIVE_LEVEUP = 20153;
    CS_MOTIVE_REFINEUP = 20154; 
    SC_MOTIVE_REFINEUP = 20155;
    CS_MOTIVE_DECOMPOSE = 20156; 
    SC_MOTIVE_DECOMPOSE = 20157;
    CS_MOTIVE_LOCK = 20158; 
    SC_MOTIVE_LOCK = 20159;
    CS_MOTIVE_UNEQUIP = 20160; 
    SC_MOTIVE_UNEQUIP = 20161;
    CS_MOTIVE_QUERY = 20162; 
    SC_MOTIVE_QUERY = 20163;
    CS_MOTIVE_BREAK = 20164; 
    SC_MOTIVE_BREAK = 20165;


    CS_BATTLE_REPORT_BATTLEEND = 20200; 
    SC_BATTLE_REPORT_BATTLEEND = 20201;
    CS_DUNGEONS_ENTER          = 20202; 
    SC_DUNGEONS_ENTER          = 20203; 
    CS_DUNGEONS_FINISH         = 20204; 
    SC_DUNGEONS_FINISH         = 20205; 
    SC_DUNGEONS_DATA_NTF       = 20206; 
    CS_DUNGEONS_ENTER_ALREADY  = 20207; 
    CS_DUNGEONS_CURRENT_DATA   = 20208; 
    SC_DUNGEONS_CURRENT_DATA   = 20209; 
    SC_DUNGEONS_ENTER_ALREADY  = 20210; 


    CS_CHAEGR_GOODS_ORDER = 20300; 
    SC_CHAEGR_GOODS_ORDER = 20301; 
    SC_CHAEGR_FINISH      = 20302; 
    CS_ACCOUNT_LOGIN_SDK  = 20303; 
    SC_ACCOUNT_LOGIN_SDK  = 20304; 
    CS_CHAEGR_GOODS_LIST  = 20305; 
    SC_CHAEGR_GOODS_LIST  = 20306; 
    CS_CHARGE_MONEY_QUERY = 20307; 
    SC_CHARGE_MONEY_QUERY = 20308; 


    CS_MAP_GET_ALL_TARGETS     = 20350; 
    SC_MAP_GET_ALL_TARGETS     = 20351; 
    CS_MAP_TRACK_TARGET        = 20352; 
    SC_MAP_TRACK_TARGET        = 20353; 
    CS_MAP_CANCEL_TRACK_TARGET = 20354; 
    SC_MAP_CANCEL_TRACK_TARGET = 20355; 


    CS_REQ_SILVER_CREATURE_LIST       = 20400; 
    SC_SILVER_CREATURE_LIST           = 20401; 
    CS_SILVER_CREATURE_COMBINE        = 20402; 
    SC_SILVER_CREATURE_COMBINE_RESULT = 20403; 
    CS_SILVER_CREATURE_RELEASE        = 20404; 
    SC_SILVER_CREATURE_RELEASE_RESULT = 20405; 
    SC_SILVER_CREATURE_CHANGE_NTF     = 20406; 
    SC_SILVER_CREATURE_COLLECT_FAIL   = 20407; 
    CS_REQ_SILVER_CREATURE_IN_BATTLE      = 20408; 
    SC_RES_SILVER_CREATURE_IN_BATTLE_RESULT = 20409; 
    CS_REQ_SILVER_CREATURE_LEAVE_BATTLE = 20410; 
    SC_RES_SILVER_CREATURE_LEAVE_BATTLE_RESULT = 20411; 


    CS_ACHIEVEMENT_REWARD = 20450; 
    SC_ACHIEVEMENT_REWARD = 20451; 
    SC_FINISH_EVENT_UPDATE = 20452; 
    CS_ACHIEVEMENT_QUERY = 20453; 
    SC_ACHIEVEMENT_QUERY = 20454; 
    CS_ACHIEVEMENT_ADD_PROGRESS = 20455; 
    SC_ACHIEVEMENT_ADD_PROGRESS = 20456; 
    CS_ACHIEVEMENT_EVENT = 20457; 
    SC_ACHIEVEMENT_EVENT = 20458; 
    

    CS_REQ_HOUSE_INFO = 20500; 
    SC_RES_HOUSE_INFO = 20501; 
    CS_REQ_BUY_HOUSE = 20502; 
    SC_RES_BUY_HOUSE = 20503; 
    CS_REQ_OPEN_HOUSE = 20504; 
    SC_RES_OPEN_HOUSE = 20505; 
    CS_REQ_UPGRADE_HOUSE = 20506; 
    SC_RES_UPGRADE_HOUSE = 20507; 
    SC_HOUSE_INCOME_NTF = 20508; 
    CS_REQ_CLAIM_HOUSE_INCOME = 20509; 
    SC_RES_CLAIM_HOUSE_INCOME = 20510; 


    CS_MONTH_CARD_QUERY = 20550; 
    SC_MONTH_CARD_QUERY = 20551; 
    SC_MONTH_CARD_REWARD_NTF = 24552; 
    SC_MONTH_CARD_OVERDUE_NTF = 20553; 


    CS_MAIL_GET_LIST = 20600;              
    SC_MAIL_GET_LIST = 20601;              
    CS_MAIL_READ = 20602;                  
    SC_MAIL_READ = 20603;
    CS_MAIL_RECV_ATTACHMENTS = 20604;      
    SC_MAIL_RECV_ATTACHMENTS = 20605;
    CS_MAIL_DEL = 20606;                   
    SC_MAIL_DEL = 20607;
    CS_MAIL_DEL_ALL_READED = 20608;        
    SC_MAIL_DEL_ALL_READED = 20609;
    CS_MAIL_RECV_ALL_ATTACHMENTS = 20610;  
    SC_MAIL_RECV_ALL_ATTACHMENTS = 20611;
    SC_MAIL_ADD_DEL_NTF = 20612;  


    CS_REQ_NOTICE_LIST = 20650; 
    SC_RES_NOTICE_LIST = 20651; 



    SC_HORDE_DATA_NTF = 20702; 
    CS_DUNGEONS_FULL_DATA = 20703;
    SC_DUNGEONS_FULL_DATA = 20704; 


    CS_SIGNIN_ACTIVITY_DATA = 20751;    
    SC_SIGNIN_ACTIVITY_DATA = 20752;    
    CS_SIGNIN_ACTIVITY_REWARD = 20753;  
    SC_SIGNIN_ACTIVITY_REWARD = 20754;  
    SC_SIGNIN_ACTIVITY_POP = 20755;     


    CS_OUTSIDE_ATTRIB_QUERY = 20800; 
    SC_OUTSIDE_ATTRIB_QUERY = 20801; 
    SC_OUTSIDE_ATTRIB_NTF = 20802; 
    CS_WANTED_BIONICS_ATTRIB_QUERY = 20803; 
    SC_WANTED_BIONICS_ATTRIB_QUERY = 20804; 
    SC_WANTED_BIONICS_ATTRIB_NTF = 20805; 


    CS_ENTER_BATTLE = 20900; 
    SC_ENTER_BATTLE = 20901; 
    CS_LEAVE_BATTLE = 20902; 
    SC_LEAVE_BATTLE = 20903; 
    CS_PAUSE_BATTLE = 20904; 
    SC_PAUSE_BATTLE = 20905; 
    CS_START_BATTLE = 20906; 
    SC_START_BATTLE = 20907; 



    CS_WANTED_OUTSIDE_DATA = 21000; 
    SC_WANTED_OUTSIDE_DATA = 21001; 
    SC_WANTED_OUTSIDE_DATA_NTF = 21002; 
    CS_ENTER_WANTED = 21003;
    SC_ENTER_WANTED = 21004;

    CS_WANTED_INSIDE_DATA = 21005; 
    SC_WANTED_INSIDE_DATA = 21006; 
    SC_WANTED_STEP_NTF = 21007; 
    CS_WANTED_CHOOSE_AWARD = 21008; 
    SC_WANTED_CHOOSE_AWARD = 21009; 
    CS_WANTED_OVER = 21010; 
    SC_WANTED_OVER = 21011; 
    CS_WANTED_STAMINA_EXCHANGE = 21012;
    SC_WANTED_STAMINA_EXCHANGE = 21013;
    CS_WANTED_RESET_POINT = 21014; 
    SC_WANTED_RESET_POINT = 21015; 
    CS_WANTED_LEAVE = 21016; 
    SC_WANTED_LEAVE = 21017; 

    CS_WANTED_BLESS_BOND_REQ = 21018; 
    SC_WANTED_BLESS_BOND_RES = 21019; 
    SC_WANTED_BLESS_NTF = 21020; 
    SC_WANTED_BOND_NTF = 21021; 
    CS_WANTED_BIONICS_REQ = 21022; 
    SC_WANTED_BIONICS_RES = 21023; 
    SC_WANTED_BIONICS_NTF = 21024; 
    SC_WANTED_RELICS_NTF = 21025; 
    CS_WANTED_RELICS_REQ = 21026; 
    SC_WANTED_RELICS_RES = 21027; 

    CS_WANTED_ADVENTURE_REQ = 21028; 
    SC_WANTED_ADVENTURE_RES = 21029; 
    CS_WANTED_ADVENTURE_CHANGE_REQ = 21030; 
    SC_WANTED_ADVENTURE_CHANGE_RES = 21031; 

    CS_WANTED_SHOP_REQ = 21032; 
    SC_WANTED_SHOP_RES = 21033; 
    CS_WANTED_SHOP_BUY_REQ = 21034; 
    SC_WANTED_SHOP_BUY_RES = 21035; 

    CS_WANTED_REVIVE_REQ = 21036; 
    SC_WANTED_REVIVE_RES = 21037; 
    CS_WANTED_RECOVER_REQ = 21038; 
    SC_WANTED_RECOVER_RES = 21039; 

    CS_WANTED_BIONIC_GIVEUP_REQ = 21040; 
    SC_WANTED_BIONIC_GIVEUP_RSP = 21041; 


    CS_BATTLE_PASS_DATA = 21100; 
    SC_BATTLE_PASS_DATA = 21101; 
    CS_BATTLE_PASS_AWARD = 21102; 
    SC_BATTLE_PASS_AWARD = 21103; 
    SC_BATTLE_PASS_NTF   = 21104;


    CS_DAILY_MISSION_QUERY = 21150;             
    SC_DAILY_MISSION_QUERY = 21151;             
    CS_DAILY_MISSION_ACTIVEPOINT_CLAIM = 21152; 
    SC_DAILY_MISSION_ACTIVEPOINT_CLAIM = 21153; 
    CS_DAILY_MISSION_REWARD_CLAIM = 21154;      
    SC_DAILY_MISSION_REWARD_CLAIM = 21155;      
    SC_DAILY_MISSION_NTF = 21156;               


    CS_REQ_REGION_PROGRESS = 21200; 
    SC_RES_REGION_PROGRESS = 21201; 
    CS_REQ_CLAIM_REWARD = 21202; 
    SC_RES_CLAIM_REWARD = 21203; 
    SC_UNLOCK_SUB_REGION_NTF = 21204; 
    SC_SUB_REGION_UPDATE_NTF = 21205; 


    CS_REQ_GUIDE_INFO = 21300; 
    SC_RES_GUIDE_INFO = 21301; 
    SC_UNLOCK_GUIDE_NTF = 21302; 
    CS_REQ_READ_GUIDE = 21303; 
    SC_RES_READ_GUIDE = 21304; 


    CS_LIMIT_GROUP_REQ = 21400; 
    SC_LIMIT_GROUP_RES = 21401; 
    SC_LIMIT_GROUP_NTF = 21402; 

    CS_PATROL_MONSTER_REQ = 21500; 
    SC_PATROL_MONSTER_RES = 21501; 
    SC_PATROL_MONSTER_NTF = 21502; 

    CS_CMD_MAX  = 49999; 
}
