syntax = "proto3";

package msg;
option  go_package = "proto/GameMsg";

enum EnmComm
{
    ENM_COMM_NONE = 0;
}


enum EnmPlatID
{
    ENM_PID_IOS     = 0; 
    ENM_PID_ANDROID = 1; 
    ENM_PID_PC      = 2; 
}


enum EnmGender
{
    ENM_GENDER_INVALID = 0; 
    ENM_GENDER_MALE    = 1; 
    ENM_GENDER_FEMALE  = 2; 
    ENM_GENDER_MAX     = 3; 
}


enum EnmRole
{
    ENM_ROLE_INVALID = 0; 
    ENM_ROLE_MAIN    = 1; 
    ENM_ROLE_SECOND  = 2; 
}

enum EnmSizeLimit
{
    option allow_alias          = true;
    reserve                     = 0;
    DENINE_WARNING              = 0;
    MAX_TOKEN_LEN               = 1024; 
    MAX_NAME_LEN                = 48;   
    MAX_ROLE_NUM_ONE_ACCOUNT    = 3;    
    MAX_USERID_LEN              = 500;  
    MAX_PASSWD_LEN              = 50;   
    MAX_UDID_SIZE               = 100;   
    MAX_ITEM_LEN                = 500;  
    MAX_ITEM_HOLE_GROUP_LEN     = 20;   
    MAX_CHARACTER_LEN           = 100;
    MAX_SAVEPOINTS              = 100; 
    MAX_EQUIP_POS               = 10;  
    MAX_DYNAMIC_COLLECTION_LEN  = 300;
    MAX_STATIC_COLLECTION_LEN   = 2000;
    MAX_LIMIT_GROUP_LEN         = 50; 
    MAX_BATTLE_PASS_LEN         = 10; 
    MAX_PATROL_MONSTER_LEN      = 100; 
    MAX_CHARACTER_TEAM_MEMBERS  = 4;  
    MAX_CHARACTER_TEAMS         = 15; 
    MAX_CHARACTER_NUMS          = 50; 
    MAX_TASKACTION_LEN          = 10;
    MAX_PROCESSING_TASKS_LEN    = 100;
    MAX_COMPLETED_TASKS_LEN     = 300;
    MAX_WHITE_ACCOUNT_OWNER_LEN = 30;
    MAX_TEMP_GLOBAL_BUFF        = 10; 
    MAX_DUNGEONS_TYPE_LEN       = 20; 
    MAX_ATTRIBUTE_COMPONENT_LEN = 10;
    MAX_ATTRIBUTE_SYSTEM_LEN    = 10;
    MAX_TEAM_NAME_LEN           = 43;   
    MAX_ATTRIBUTE_NUM           = 150;  
    MAX_TRACKED_TARGETS_LEN     = 4;    
    MAX_CHARGE_LEN              = 300;  
    MAX_GOODS_ORDER_LEN         = 100;  
    MAX_ONLINE_BRIEF_ADDR_LEN   = 32;   
    MAX_MSG_PKG_BODY_LEN        = 8096; 
    MAX_RETRY_PASS_REQ_LIST_LEN = 5;    
    MAX_CASES_LEN               = 10;   
    MAX_CLUES_LEN               = 100;  
    MAX_GACHA_POOL_NUMS         = 20;   
    MAX_EVENT_FINISH_LEN        = 1000; 
    MAX_HOUSE_LEN               = 300;  
    MAX_HOUSE_MAIL_LEN          = 100;  
    MAX_BATTLE_MAP_LEN          = 300;  
    MAX_GEM_SLOTS               = 3;    
    MAX_CHARGE_MONEY_LEN        = 32;   
    MAX_MONTH_CARD_NUM          = 4;    
    MAX_MAIL_LEN                = 1000; 
    MAX_MAIL_ATTACHMENTS_LEN    = 20;   
    MAX_MAIL_CONTENT_PARAMS_LEN = 20;   
    MAX_MAIL_TITLE_LEN = 201; 
    MAX_MAIl_FROM_LEN = 41; 
    MAX_MAIL_CONTENT_LEN = 2001; 
    MAX_SYS_MAIL_RECORD_LEN     = 2000; 
    MAX_RCV_COND_MAIL_RECORD_LEN = 1000; 
    MAX_MOTIVE_ELEM_NUM         = 3000; 
    MAX_CHECK_TEXT_LEN          = 200;  
    MAX_HORDE_NUM               = 100;  
    MAX_COMMON_ITEM_LEN         = 500;  
    MAX_UNLOCK_ITEM_LEN         = 1000; 
    MAX_SILVER_CREATURE_LEN     = 50;   
    MAX_GACHA_COLLECT_POOL_NUMS = 10;   
    MAX_ITEM_CD_TYPE_LEN        = 20;   

    MAX_WANTED_TYPE_LEN         = 10; 
    MAX_WANTED_LEN              = 20; 
    MAX_WANTED_STEP_ATGS_LEN    = 5; 
    MAX_WANTED_BLESS_LEN        = 20; 
    MAX_WANTED_BIONICS_LEN      = 10; 
    MAX_WANTED_BOND_LEN         = 20; 
    MAX_WANTED_RELICS_LEN       = 20; 
    MAX_WANTED_BATTLE_WIN_AWARD_LEN = 20; 
    MAX_WANTED_CHOOSE_AWARD_INFOS_LEN = 5; 
    MAX_WANTED_CHOOSE_EVENT_LEN = 5; 
    MAX_WANTED_CHOOSE_AWARD_COUNT = 5; 
    MAX_WANTED_QUEUE_AWARD_IDS_LEN = 20; 
    MAX_WANTED_EVENT_HISTORY_LEN = 20; 
    MAX_WANTED_DIFFICULTY_LEN = 20; 
    MAX_UNLOCK_TELEPORT_LEN    = 1000; 
    MAX_WANTED_ADVENTURE       = 10;
    MAX_WANTED_NPC_MAX       = 20;
    MAX_WANTED_STAMINA       = 5;
    MAX_WANTED_SHOP          = 5;
    MAX_WANTED_SHOP_GOODS    = 30;
    MAX_WANTED_RECOVER       = 5;
    MAX_WANTED_REVIVE       = 5;
    MAX_WANTED_EFFECT_LEN   = 20;
    MAX_WANTED_ATTR_LEN     = 20;
    MAX_WANTED_UNLOCKED_BLESS_POOL_LEN = 1000; 
    MAX_WANTED_UNLOCKED_RELIC_POOL_LEN = 1000; 
    MAX_WANTED_UNLOCKED_BIONIC_POOL_LEN = 500; 

    MAX_DAILY_MISSION_REWARD_LEN = 10; 
    MAX_DAILY_MISSION_LIST_LEN   = 30; 

    MAX_SIGNIN_ACTIVITY_DAY_NUM         = 30;   
    MAX_SIGNIN_ACTIVITY_INSTANCE_NUM    = 5; 

    MAX_SUB_REGION_SEQUENCE_LEN = 50; 
    MAX_SUB_REGION_LEN = 10; 
    MAX_REGION_LEN = 10; 
    MAX_PROGRESS_VALUE_LEN = 5; 

    MAX_GUIDE_LEN = 300; 
    MAX_MISC_PB_STR_LEN = 1000000; 
    MAX_TMP_TEAM_LEN = 32; 
    MAX_ELEMENT_LEN = 8; 

    MAX_UNLOCK_SYSTEM_LEN = 200; 

    MAX_BATTLE_NUMS = 100; 
}
enum EPackType
{
    EPACKTYPE_MIN             = 0;
    EPACKTYPE_MAIN            = 1; 
    EPACKTYPE_EQUIP           = 2; 
    EPACKTYPE_TEMP_MAIN       = 3; 
    EPACKTYPE_SILVER_CREATURE = 4; 
    EPACKTYPE_GEM             = 5; 
    EPACKTYPE_MAX             = 6; 
}

enum ESource
{
    ESOURCE_MIN     = 0;
    ESOURCE_NORMAL  = 1;
    ESOURCE_PACKAGE = 2;
}



enum EnmTextCode
{

    ENM_TEXT_reserve                        = 0;
    ENM_TEXT_ACC_LOGIN_SERVER_NOT_OPEN_FAIL = 1001; 
    ENM_TEXT_ACC_LOGIN_NOT_IN_WHITE_LIST    = 1002; 
    ENM_TEXT_ACC_LOGIN_ACCOUNT_BAN          = 1003; 
    ENM_TEXT_ACC_LOGIN_VERSION_NOT_MATCH    = 1004; 
    ENM_TEXT_ACC_LOGIN_IP_NOT_ALLOW         = 1005; 
    ENM_TEXT_ACC_LOGIN_ACCOUNT_DATA_FAIL    = 1006; 
    ENM_TEXT_ACC_LOGIN_ACCOUNT_ONLINE       = 1007; 
    ENM_TEXT_ACC_LOGIN_ACCOUNT_EMPTY        = 1008; 
    ENM_TEXT_ACC_LOGIN_ACCOUNT_PASSWD_ERR   = 1009; 
    ENM_TEXT_ACC_LOGIN_ACCOUNT_PASSWD_EMPTY = 1010; 

    ENM_TEXT_CREATE_ROLE_RET_NAME_EXIST            = 1011; 
    ENM_TEXT_CREATE_ROLE_RET_INIT_ROLE_DATA_FAIL   = 1012; 
    ENM_TEXT_NOT_ACC_LOGIN                         = 1013; 
    ENM_TEXT_CREATE_ROLE_RET_INSERT_ROLE_DATA_FAIL = 1014; 

    ENM_TEXT_TABLE_NOT_FOUND               = 1015;
    ENM_TEXT_PLAYER_CACACHE_ITEM_NOT_FOUND = 1016;
    ENM_TEXT_PLAYER_NULL                   = 1017;

    ENM_TEXT_EQUIP_NOT_THISTYPE   = 1029;
    ENM_TEXT_ACC_LOGIN_REPEAT     = 1030; 
    ENM_TEXT_ITEM_TYPE_MISMATCH   = 1031;
    ENM_TEXT_STAMINA_NOT_ENOUGH   = 1032; 
    ENM_TEXT_STAMINA_RECOVER_MAX  = 1033; 
    ENM_TEXT_ACC_LOGIN_ELSEWHERE  = 1034; 
    ENM_TEXT_ILLEGAL_ROLE_NAME    = 1035; 
    ENM_TEXT_ROLELOGIN_SCENE_FAIL = 1036; 

    ENM_TEXT_WORD_CHECK_FAILED = 1042; 


    ENM_TEXT_ITEM_LIMITTYPE_MAX   = 1018;
    ENM_TEXT_ITEM_HOLD_MAX        = 1019; 
    ENM_TEXT_ITEM_NOT_ENOUGH      = 1020; 
    ENM_TEXT_ITEM_NO_USEHANDLER   = 1021; 
    ENM_TEXT_PACKAGE_FULL         = 1022;
    ENM_TEXT_PACKAGE_ILEGAL_SUB   = 1023;
    ENM_TEXT_PACKAGE_ILEGAL_PARAM = 1024;
    ENM_TEXT_PACKAGE_SUB_FAIL     = 1025;
    ENM_TEXT_PACKAGE_NIL          = 1026;
    ENM_TEXT_PACKAGE_ITEM_NIL     = 1027;
    ENM_TEXT_PACKAGE_OP_FREEQUENT = 1028;
    ENM_TEXT_ITEM_USE_TOO_MUCH    = 1040; 
    ENM_TEXT_ITEM_USE_ZERO        = 1041; 
    ENM_TEXT_ITEM_CD              = 1060;
    ENM_TEXT_ITEM_ADD_FAIL_TO_MAIL = 1070;

    ENM_TEXT_GENDER_PARAM_WRONG         = 1043; 
    ENM_TEXT_ROLE_NAME_SETTED           = 1044; 
    ENM_TEXT_ROLE_NAME_TOO_LONG         = 1045; 
    ENM_TEXT_CHECK_TEXT_ILLEGAL         = 1046; 
    ENM_TEXT_CHECK_EVENT_TYPE_NOT_EXIST = 1047; 
    ENM_TEXT_ROLE_NAME_SAME             = 1048; 
    ENM_TEXT_GENDER_SETTED              = 1049; 

    ENM_TEXT_WRONG_PARAM                  = 1051;
    ENM_TEXT_REDIS_OP_FAIL                = 1055;
    ENM_TEXT_ACC_LOGIN_BAD_CLIENT_VERSION = 1056; 


    ENM_TEXT_COLLECTION_NO_DATA     = 1050; 
    ENM_TEXT_COLLECTION_ALREADY_OP  = 1052; 
    ENM_TEXT_COLLECTION_COND_UNMEET = 1053; 
    ENM_TEXT_COLLECTION_OP_ILEGAL   = 1054; 

    ENM_TEXT_COLLECTION_REQ_TOO_FREQUENT = 1058; 
    ENM_TEXT_COUNT_GROUP_LIMIT = 1059; 


    ENM_TEXT_CHARACTER_EXP_FULL                          = 1100; 
    ENM_TEXT_CHARACTER_STAR_FULL                         = 1101; 
    ENM_TEXT_CHARACTER_NOT_EXIST                         = 1102; 
    ENM_TEXT_CHARACTER_CANNOT_GROW                       = 1103; 
    ENM_TEXT_CHARACTER_INVALID_TEAMID                    = 1104; 
    ENM_TEXT_CHARACTER_INVALID_TEAM_MEMBER_INDEX         = 1105; 
    ENM_TEXT_CHARACTER_TEAM_MEMBER_NO_SWITCH             = 1106; 
    ENM_TEXT_CHARACTER_TEAM_NO_SWITCH                    = 1107; 
    ENM_TEXT_CHARACTER_TEAM_CANNOT_SWITCH_NOW            = 1108; 
    ENM_TEXT_CHARACTER_MEMBER_CANNOT_SWITCH_NOW          = 1109; 
    ENM_TEXT_CHARACTER_TEAM_CANNOT_MODIFY_NOW            = 1110; 
    ENM_TEXT_CHARACTER_NO_MEMBER_IN_TARGET_TEAM          = 1111; 
    ENM_TEXT_CHARACTER_CANNOT_CLEAR_MEMBERS_IN_MAIN_TEAM = 1112; 
    ENM_TEXT_CHARACTER_NOBODY_SIT_AT_INDEX               = 1113; 
    ENM_TEXT_CHARACTER_TEAM_NAME_TOO_LONG                = 1114; 
    ENM_TEXT_TEAM_EXP_FULL                               = 1115; 
    ENM_TEXT_CHARACTER_LEVEL_LIMIT                       = 1116; 
    ENM_TEXT_CHARACTER_ALREADY_EXIST                     = 1117; 
    ENM_TEXT_CHARACTER_TEAM_MEMBER_DUPLICATE             = 1118; 
    ENM_TEXT_CHARACTER_TEAM_GEM_NOT_OWNED                = 1119; 
    ENM_TEXT_CHARACTER_TEAM_GEM_DUPLICATE                = 1120; 
    ENM_TEXT_CHARACTER_TEAM_GEM_COST_NOT_ENOUGH          = 1121; 
    ENM_TEXT_CHARACTER_TEAM_GEM_NOT_EXIST                = 1122; 
    ENM_TEXT_CHARACTER_TEAM_GEM_ELEMENT_LIMIT            = 1123; 
    ENM_TEXT_CHARACTER_TEAM_GEM_SIZE_NOT_MATCH           = 1124; 
    ENM_TEXT_CHARACTER_TEAM_GEM_STATE_INVALID            = 1125; 
    ENM_TEXT_CHARACTER_IS_ALIVE                          = 1126; 
    ENM_TEXT_CHARACTER_TEAM_MEMBER_ALL_DEAD              = 1127; 
    ENM_TEXT_CHARACTER_IS_DEAD                           = 1128; 


    ENM_TEXT_STEP_ID_INVALID       = 1200; 
    ENM_TEXT_TASK_ID_INVALID       = 1201; 
    ENM_TEXT_ACTION_NOT_PROCESSING = 1202; 
    ENM_TEXT_ACTION_ID_NOT_FOUND   = 1203; 
    ENM_TEXT_TASK_IS_FINISHED      = 1204; 
    ENM_TEXT_TASK_IS_PROCESSING    = 1205; 
    ENM_TEXT_TASK_ID_NOT_FOUND     = 1206; 
    ENM_TEXT_TASK_NO_STEP          = 1207; 
    ENM_TEXT_STEP_ID_NOT_FOUND     = 1208; 
    ENM_TEXT_TASK_NOT_PROCESSING   = 1209; 
    ENM_TEXT_TASK_STEP_FAILED      = 1210; 
    ENM_TEXT_TASK_STEP_PROCESSING  = 1211; 


    ENM_TEXT_ARRAY_PUSH_FAIL = 1300; 
    ENM_TEXT_POINT_NULL      = 1301; 
    ENM_MGR_NOT_FOUND        = 1302; 
    ENM_TEXT_INVALID_ARGS    = 1303; 
    ENM_TEXT_BAD_ALLOC       = 1304; 


    ENM_TEXT_MAP_INST_NOT_FOUND   = 1500; 
    ENM_TEXT_MAP_CONF_NOT_FOUND   = 1501; 
    ENM_TEXT_MAP_CONDITION        = 1502; 
    ENM_TEXT_MAP_PLAYER_COUNT_MAX = 1503; 
    ENM_TEXT_MAP_LINE_NOT_FOUND   = 1504; 


    ENM_TEXT_DUNGEONS_COUNT_MAX     = 1600; 
    ENM_TEXT_WORLD_LEVEL_NOT_ENOUGH = 1601; 
    ENM_TEXT_DUNGEONS_FAIL          = 1602; 
    ENM_TEXT_DUNGEONS_TYPE_WRONG    = 1603; 
    ENM_TEXT_DUNGEONS_IN            = 1604; 
    ENM_TEXT_DUNGEONS_NOT_IN        = 1605; 


    ENM_TEXT_SKILL_NOT_EXIST            = 1700; 
    ENM_TEXT_SKILL_LEVEL_LIMIT          = 1701; 
    ENM_TEXT_SKILL_NOT_BELONG_CHARACTER = 1702; 
    ENM_TEXT_TALENT_FULL                = 1703; 
    ENM_TEXT_TALENT_NODE_INVALID        = 1704; 
    ENM_TEXT_TALENT_CONTENT_INVALID     = 1705; 
    ENM_TEXT_TALENT_DUPLICATED          = 1706; 
    ENM_TEXT_TALENT_PARENT_LOCKED       = 1707; 
    ENM_TEXT_TALENT_ALREADY_UNLOCKED    = 1708; 
    ENM_TEXT_CHARACTER_NO_SKILLS        = 1709; 

    ENM_TEXT_SDK_SIGN_WRONG         = 1800; 
    ENM_TEXT_SDK_GOODS_TIME_INVALID = 1801; 
    ENM_TEXT_SDK_GOODS_NOT_FOUND    = 1802; 
    ENM_TEXT_SDK_GOODS_PRICE_WRONG  = 1803; 
    ENM_TEXT_SDK_PARAMS_WRONG       = 1804; 
    ENM_TEXT_SDK_LOGIN_TOKEN_WRONG  = 1805; 


    ENM_TEXT_BUFF_FULL       = 1900; 
    ENM_TEXT_BUFF_NOT_EXIST  = 1901; 
    ENM_TEXT_BUFF_INVALID    = 1902; 
    ENM_TEXT_BUFF_DUPLICATED = 1903; 
    ENM_TEXT_BUFF_EXPIRED    = 1904; 


    ENM_TEXT_COST_NOT_ENOUGH              = 2000; 
    ENM_TEXT_SILVER_CREATURE_PACKAGE_FULL = 2001; 
    ENM_TEXT_CANNOT_COMBINE               = 2002; 
    ENM_TEXT_SILVER_CREATURE_NOT_FOUND    = 2003; 


    ENM_TEXT_MONEY_INVALID_TYPE        = 2100; 
    ENM_TEXT_MONEY_INVALID_NUM         = 2101; 
    ENM_TEXT_MONEY_NOT_ENOUGH          = 2102; 
    ENM_TEXT_SHOP_NOT_EXSIT            = 2110; 
    ENM_TEXT_SHOP_INVALID_TYPE         = 2111; 
    ENM_TEXT_SHOP_GOODS_NOT_EXSIT      = 2112; 
    ENM_TEXT_SHOP_GOODS_NOT_ENOUGH     = 2113; 
    ENM_TEXT_SHOP_GOODS_PAY_TYPE_ERROR = 2114; 
    ENM_TEXT_SHOP_INVALID_BOUGHT_NUM   = 2115; 
    ENM_TEXT_SHOP_GOODS_LIST_CD_ERROR  = 2116; 


    ENM_TEXT_ACHIEVEMENT_NOT_FOUND        = 2200; 
    ENM_TEXT_ACHIEVEMENT_NOT_FINISHED     = 2201; 
    ENM_TEXT_ACHIEVEMENT_ALREADY_REWARD   = 2202; 
    ENM_TEXT_ACHIEVEMENT_REWARD_NOT_FOUND = 2203; 
    ENM_TEXT_ACHIEVEMENT_CAN_NOT_JUDGE    = 2204; 
    ENM_TEXT_ACHIEVEMENT_ALREADY_FINISHED = 2205; 
    ENM_TEXT_NOT_UNLOCK                   = 2206; 
    ENM_TEXT_ACHIEVEMENT_MAX_COUNT        = 2207; 
    ENM_TEXT_ACHIEVEMENT_INVALID_EVENT    = 2208; 


    ENM_TEXT_HOUSE_NOT_UNLOCK          = 2300; 
    ENM_TEXT_HOUSE_ALREADY_OWN         = 2301; 
    ENM_TEXT_HOUSE_NOT_EXIST           = 2302; 
    ENM_TEXT_HOUSE_NOT_ENOUGH_CURRENCY = 2303; 
    ENM_TEXT_HOUSE_NO_INCOME             = 2304; 
    ENM_TEXT_CENTRAL_HOUSE_NOT_OPEN = 2305; 
    ENM_TEXT_HOUSE_ALREADY_OPEN = 2306; 
    ENM_TEXT_HOUSE_NOT_BUY = 2307; 
    ENM_TEXT_HOUSE_SURROUND_CANNOT_UPGRADE = 2308; 
    ENM_TEXT_HOUSE_NOT_OPEN = 2309; 


    ENM_TEXT_NULL_POOL_DATA    = 2400; 
    ENM_TEXT_GACHA_COST_ERR    = 2401; 
    ENM_TEXT_GACHA_REWARDS_GET = 2402; 
    ENM_TEXT_GACHA_TIME_ERR    = 2403; 
    ENM_TEXT_GACHA_DAILY_LIMIT = 2404; 
    ENM_TEXT_GACHA_DROP_ERR    = 2405; 
    ENM_TEXT_GACHA_REBATE_ERR  = 2406; 


    ENM_TEXT_MONTH_CARD_ID_INVALID  = 2500; 
    ENM_TEXT_MONTH_CARD_DAY_UPLIMIT = 2501; 


    ENM_TEXT_MOTIVE_ALEARY_EQUIPED       = 2600; 
    ENM_TEXT_MOTIVE_UID_INVALID          = 2601; 
    ENM_TEXT_MOTIVE_LEVEL_ALEARY_REACHED = 2602; 
    ENM_TEXT_MOTIVE_LEVEL_REACHED_MAX    = 2603; 
    ENM_TEXT_MOTIVE_REFINE_MAX           = 2604; 
    ENM_TEXT_MOTIVE_EQUIPED              = 2605; 
    ENM_TEXT_MOTIVE_REPEAT               = 2606; 
    ENM_TEXT_MOTIVE_LOCKED               = 2607; 
    ENM_TEXT_MOTIVE_DECOMPOSE_SSR        = 2608; 

    ENM_TEXT_MOTIVE_LEVELUP_USE_SELF     = 2620; 
    ENM_TEXT_MOTIVE_LEVELUP_ITEM_INVALID = 2621; 
    ENM_TEXT_MOTIVE_CONF_INVALID         = 2622; 
    ENM_TEXT_MOTIVE_NEED_BREAK           = 2623; 
    ENM_TEXT_MOTIVE_LEVELUP_CANNOT       = 2624; 
    ENM_TEXT_MOTIVE_LEVELUP_MONEY_NOT_ENOUGH = 2625; 
    ENM_TEXT_MOTIVE_LEVELUP_COST_ITEM_FAILED = 2626; 
    ENM_TEXT_MOTIVE_LEVELUP_COST_MONEY_FAILED = 2627; 
    ENM_TEXT_MOTIVE_LEVELUP_COST_MOTIVE_FAILED = 2628; 
    
    ENM_TEXT_MOTIVE_BREAK_REACHED_MAX    = 2640; 
    ENM_TEXT_MOTIVE_NEED_LEVEL_UP        = 2641; 
    ENM_TEXT_MOTIVE_BREAK_NEED_WORLD_LEVEL = 2642; 
    ENM_TEXT_MOTIVE_BREAK_MONEY_NOT_ENOUGH = 2643; 
    ENM_TEXT_MOTIVE_BREAK_ITEM_NOT_ENOUGH  = 2644; 
    ENM_TEXT_MOTIVE_BREAK_COST_ITEM_FAILED = 2645; 
    ENM_TEXT_MOTIVE_BREAK_COST_MONEY_FAILED = 2646; 


    ENM_TEXT_CHARGE_GOODS_LIST_CD_ERROR = 2700; 
    ENM_TEXT_CHARGE_GOODS_ORDER_CD_ERROR = 2701; 
    ENM_TEXT_GIFT_GOODS_NOT_EXSIT = 2702; 
    ENM_TEXT_GIFT_GOODS_NOT_ENOUGH = 2703; 


    ENM_TEXT_WANTED_IS_IN_WANTED   = 2800;
    ENM_TEXT_WANTED_NOT_IN_WANTED   = 2801;
    ENM_TEXT_WANTED_MAX_STEP    = 2802;
    ENM_TEXT_WANTED_EXCHANGE_WRONG_STATUS    = 2803;
    ENM_TEXT_WANTED_EXCHANGE_REPEATED    = 2804;
    ENM_TEXT_WANTED_STEP_WRONG_AWARD    = 2805;
    ENM_TEXT_WANTED_BIONICS_REPLACE_ID_NOT_EXIST = 2806;

    ENM_TEXT_WANTED_ADVENTURE_ALREADY_EXISTS = 2807;
    ENM_TEXT_WANTED_ADVENTURE_NOT_EXISTS = 2808;
    ENM_TEXT_WANTED_ADVENTURE_CONTENT_INVALID = 2809;
    ENM_TEXT_WANTED_ADVENTURE_OPTION_INVALID = 2810;
    ENM_TEXT_WANTED_ADVENTURE_NOT_COMPLETE = 2819;

    ENM_TEXT_WANTED_STAMINA_ALREADY_EXISTS = 2811;
    ENM_TEXT_WANTED_STAMINA_NOT_EXISTS = 2812;

    ENM_TEXT_WANTED_SHOP_ALREADY_EXISTS = 2813;
    ENM_TEXT_WANTED_SHOP_NOT_EXISTS = 2814;
    ENM_TEXT_WANTED_SHOP_GOODS_COUNT_NOT_ENOUGH = 2815;
    ENM_TEXT_WANTED_SHOP_GOODS_NOT_EXISTS = 2816;
    ENM_TEXT_WANTED_SHOP_MONEY_NOT_ENOUGH = 2817;
    ENM_TEXT_WANTED_BLESS_REPEATED = 2830;
    ENM_TEXT_WANTED_RELIC_REPEATED = 2831;
    ENM_TEXT_WANTED_RELIC_NOT_EXISTS = 2832;

    ENM_TEXT_WANTED_RECOVER_ALREADY_EXISTS = 2833;
    ENM_TEXT_WANTED_RECOVER_NOT_EXISTS = 2834;
    ENM_TEXT_WANTED_RECOVER_FINISHED = 2835;

    ENM_TEXT_WANTED_REVIVE_ALREADY_EXISTS = 2836;
    ENM_TEXT_WANTED_REVIVE_NOT_EXISTS = 2837;
    ENM_TEXT_WANTED_REVIVE_FINISHED = 2838;
    ENM_TEXT_WANTED_REVIVE_ALL_FAILED = 2839;

    ENM_TEXT_WANTED_EFFECT_ALREADY_EXISTS = 2850;
    ENM_TEXT_WANTED_EFFECT_NOT_EXISTS = 2851;


    ENM_TEXT_BATTLE_ALEARDY_EXIST       = 2900; 
    ENM_TEXT_BATTLE_TYPE_INVALID        = 2901; 
    ENM_TEXT_BATTLE_ID_INVALID          = 2902; 
    ENM_TEXT_BATTLE_STATE_NOT_MATCH     = 2903; 
    ENM_TEXT_BATTLE_STATE_FORBID        = 2904; 
    ENM_TEXT_BATTLE_PASS_TIME_TOO_SHORT = 2905; 


    ENM_TEXT_TELEPORT_ALREADY_UNLOCK            = 3000; 
    ENM_TEXT_TELEPORT_NOT_EXIST                 = 3001; 
    ENM_TEXT_TELEPORT_MAPID_INVALID             = 3002; 
    ENM_TEXT_TELEPORT_POS_RANGE_INVALID         = 3003; 
    ENM_TEXT_TELEPORT_UNLOCK_FAILED             = 3004; 
    ENM_TEXT_TELEPORT_NOT_UNLOCKED              = 3005; 
    

    ENM_TEXT_DAILY_MISSION_ID_INVALID           = 3100; 
    ENM_TEXT_DAILY_MISSION_ID_NOT_FINISH      = 3101; 
    ENM_TEXT_DAILY_MISSION_ID_HAS_CLAIMED     = 3102; 
    ENM_TEXT_DAILY_MISSION_REWARD_ID_INVALID    = 3103; 
    ENM_TEXT_DAILY_MISSION_REWARD_NOT_FOUND     = 3104; 


    ENM_TEXT_NOT_SIGNIN_ACTIVITY                    = 3200; 
    ENM_TEXT_SIGNIN_ACTIVITY_NOT_OPENTIME           = 3201; 
    ENM_TEXT_SIGNIN_ACTIVITY_NOT_UNLOCKED           = 3202; 
    ENM_TEXT_SIGNIN_ACTIVITY_CANNOT_CLAIM_REWARD    = 3203; 
    ENM_TEXT_SIGNIN_ACTIVITY_REWARD_INVALID         = 3204; 
    ENM_TEXT_SIGNIN_ACTIVITY_ID_INVALID             = 3205; 


    ENM_TEXT_SUB_REGION_NO_AVAILABLE_REWARDS = 3300; 


    ENM_TEXT_GUIDE_ID_NOT_UNLOCKED             = 3400; 
    

    ENM_TEXT_CHARACTER_LEVEL_UP_ITEMS_EMPTY             = 3500; 
    ENM_TEXT_CHARACTER_LEVEL_UP_CONF_INVALID            = 3501; 
    ENM_TEXT_CHARACTER_LEVEL_UP_MAX_LIMIT               = 3502; 
    ENM_TEXT_CHARACTER_LEVEL_UP_NEED_BREAK              = 3503; 
    ENM_TEXT_CHARACTER_LEVEL_UP_ITEM_INVALID            = 3504; 
    ENM_TEXT_CHARACTER_LEVEL_UP_FAILED                  = 3505; 
    ENM_TEXT_CHARACTER_LEVEL_UP_COST_ITEM_FAILED        = 3506; 
    ENM_TEXT_CHARACTER_LEVEL_UP_COST_MONEY_FAILED       = 3507; 

    ENM_TEXT_CHARACTER_LEVEL_BREAK_CONF_INVALID           = 3550; 
    ENM_TEXT_CHARACTER_LEVEL_BREAK_NEED_LEVEL_UP          = 3551; 
    ENM_TEXT_CHARACTER_LEVEL_BREAK_LEVEL_MAX_LIMIT        = 3552; 
    ENM_TEXT_CHARACTER_LEVEL_BREAK_NEED_WORLD_LEVEL       = 3553; 
    ENM_TEXT_CHARACTER_LEVEL_BREAK_MONEY_NOT_ENOUGH       = 3554; 
    ENM_TEXT_CHARACTER_LEVEL_BREAK_COST_ITEM_FAILED       = 3555; 
    ENM_TEXT_CHARACTER_LEVEL_BREAK_COST_MONEY_FAILED      = 3556; 


    ENM_TEXT_BATTLE_PASS_NOT_EXIST                        = 3600; 
    ENM_TEXT_BATTLE_PASS_LEVEL_AWARD                      = 3601; 


    ENM_TEXT_MAIL_ATTACHMENT_ALREADY_RECV = 3900;  
}




enum EnmItemReason
{
    ENM_ITEM_CHANGE_MIN                       = 0;
    ENM_ITEM_CHANGE_SHOP                      = 1;  
    ENM_ITEM_CHANGE_GM                        = 2;  
    ENM_ITEM_CHANGE_USE                       = 3;  
    ENM_ITEM_CHANGE_CHARACTER_LEVEL_UP        = 4;  
    ENM_ITEM_CHANGE_INIT                      = 5;  
    ENM_ITEM_CHANGE_NORMAL                    = 6;  
    ENM_ITEM_CHANGE_BATTLE_END                = 7;  
    ENM_ITEM_CHANGE_NEW_CHARACTER_INIT_WEAPON = 8;  
    ENM_ITEM_CHANGE_TASK                      = 9;  
    ENM_ITEM_CHANGE_TASK_ACTION_ADD           = 10; 
    ENM_ITEM_CHANGE_TASK_ACTION_COST          = 11; 
    ENM_ITEM_CHANGE_COLLECT                   = 12; 
    ENM_ITEM_CHANGE_DUNGEONS_END              = 13; 
    ENM_ITEM_CHANGE_TALENT                    = 14; 
    ENM_ITEM_CHANGE_SILVER_CREATURE_COMBINE   = 15; 
    ENM_ITEM_CHANGE_ACHIEVEMENT               = 16; 
    ENM_ITEM_CHANGE_HOUSE_INDUSTRY_DROP       = 17; 
    ENM_ITEM_CHANGE_GACHA_REWARD              = 18; 
    ENM_ITEM_CHANGE_MOTIVE_LEVEL_UP           = 19; 
    ENM_ITEM_CHANGE_MOTIVE_REFINE_UP          = 20; 
    ENM_ITEM_CHANGE_DECOMPOSE_MOTIVES         = 21; 
    ENM_ITEM_CHANGE_MOTIVE_LOCK_OR_UNLOCK     = 22; 
    ENM_ITEM_CHANGE_MAIL                      = 23; 
    ENM_ITEM_CHANGE_CHARACTER_CONVERT         = 24; 
    ENM_ITEM_CHANGE_MONTHCARD_DELIVER         = 25; 
    ENM_ITEM_CHANGE_MONTHCARD_CHARGE          = 26; 
    ENM_ITEM_CHANGE_SHOP_BUY                  = 27; 
    ENM_ITEM_CHANGE_GIFT_DELIVER              = 28; 
    ENM_ITEM_CHANGE_WANTED_EXCHANGE           = 29; 
    ENM_ITEM_CHANGE_WANTED_OVER               = 30; 
    ENM_ITEM_CHANGE_DAILY_MISSION_REWARD      = 31; 
    ENM_ITEM_CHANGE_SIGNIN_ACTIVITY           = 32; 
    ENM_ITEM_CHANGE_REGION_PROGRESS           = 33; 
    ENM_ITEM_CHANGE_GUIDE                     = 34; 
    ENM_ITEM_CHANGE_NEW_CHARACTER             = 35; 
    ENM_ITEM_CHANGE_CHARACTER_LEVELUP_RECYCLE = 36; 
    ENM_ITEM_CHANGE_CHARACTER_BREAK           = 37; 
    ENM_ITEM_CHANGE_MOTIVE_BREAK              = 38; 
    ENM_ITEM_CHANGE_MOTIVE_LEVEL_UP_RECYCLE   = 39; 
    ENM_ITEM_CHANGE_BATTLE_PASS_LEVEL_AWARD   = 40; 
    ENM_ITEM_CHANGE_HOUSE_UPGRADE                              = 41;  
    ENM_ITEM_CHANGE_HOUSE_BUY                                  = 42;  
    ENM_ITEM_CHANGE_HOUSE_INCOME                               = 43;  
    ENM_ITEM_CHANGE_GACHA_REVERT_FOR_ADDITEM_FAIL              = 44; 
    ENM_ITEM_CHANGE_GACHA_REVERT_FOR_AWARDS_EMPTY              = 45; 
    ENM_ITEM_CHANGE_GACHA_COST                                 = 46; 
    ENM_ITEM_CHANGE_ITEM_USE_EFFECT                            = 47; 
    ENM_ITEM_CHANGE_DUNGEONS_FINISH_COST                       = 48; 
    ENM_ITEM_CHANGE_WANTED_SHOP_BUY                            = 49; 
    ENM_ITEM_CHANGE_WANTED_REVIVE                              = 50; 
    ENM_ITEM_CHANGE_DAILY_MISSION_FINISH_CLAIM                 = 51; 
    ENM_ITEM_CHANGE_WANTED_ADVENTURE                           = 52; 
    ENM_ITEM_CHANGE_WANTED_STEP                                = 53; 
    ENM_ITEM_CHANGE_WANTED_DISCART                             = 54; 
    ENM_ITEM_CHANGE_TIMER_RECOVER_STAMINA                      = 55; 
}


enum EnmMapType
{                               
    ENM_MAP_WORLD          = 0; 
    ENM_MAP_WORLD_BATTLE   = 1; 
    ENM_MAP_PARALLEL_WORLD = 2; 
}


enum EnmBornPosType
{
    ENM_BORN_SAVE_POINT  = 0; 
    ENM_BORN_POSITION    = 1; 
    ENM_BORN_DEFAULT_POS = 2; 
    ENM_BORN_TELEPORT    = 3; 
}


enum EnmPeriodType
{
    ENM_PERIOD_NONE    = 0; 
    ENM_PERIOD_DAILY   = 1; 
    ENM_PERIOD_WEEKLY  = 2; 
    ENM_PERIOD_MONTHLY = 3; 
    ENM_PERIOD_FOREVER = 4; 
}


enum EnmTaskActionUpdateType
{
    ETASK_ACTION_UPDATE_TYPE_NORMAL  = 0; 
    ETASK_ACTION_UPDATE_TYPE_NEW     = 1; 
    ETASK_ACTION_UPDATE_TYPE_FINISH  = 2; 
    ETASK_ACTION_UPDATE_TYPE_FAIL    = 3; 
    ETASK_ACTION_UPDATE_TYPE_RECONNECT   = 4; 
    ETASK_ACTION_UPDATE_TYPE_REMOVED = 5; 
}

enum EMailType
{
    ENM_MAIL_TYPE_INVALID  = 0;
    ENM_MAIL_TYPE_SYS      = 1; 
    ENM_MAIL_TYPE_TEMPLATE = 2; 
}

enum FenceEventType
{
    ENM_FENCE_EVENT_INVALID = 0;
    ENM_FENCE_EVENT_NAME    = 1;
    ENM_FENCE_EVENT_CMT     = 2;
    ENM_FENCE_EVENT_ART     = 3;
    ENM_FENCE_EVENT_CHAT    = 4;
    ENM_FENCE_EVENT_MAX     = 5;
}

enum EBattleType
{
    ENM_BATTLE_TYPE_INVALID  = 0;
    ENM_BATTLE_TYPE_EXPOSE   = 1; 
    ENM_BATTLE_TYPE_PATROL   = 2; 
    ENM_BATTLE_TYPE_WORLD_BOSS = 3; 
    ENM_BATTLE_TYPE_BOSS = 4; 
    ENM_BATTLE_TYPE_REPEAT_DUNGEON = 5; 
    ENM_BATTLE_TYPE_WEEK_DUNGEON = 6; 
    ENM_BATTLE_TYPE_WANTED = 7; 
    ENM_BATTLE_TYPE_HORDE = 8; 
    ENM_BATTLE_TYPE_MAX      = 9;
}

enum EBattleResultType
{
    ENM_BATTLE_RESULT_TYPE_INVALID  = 0;
    ENM_BATTLE_RESULT_TYPE_SUCCESS   = 1; 
    ENM_BATTLE_RESULT_TYPE_DEAD_FAIL   = 2; 
    ENM_BATTLE_RESULT_TYPE_TIMEOUT_FAIL = 3; 
    ENM_BATTLE_RESULT_TYPE_FORCE_FAIL = 4; 
}

enum EnmWantedStepStatus
{
    ENM_WSS_START = 0; 
    ENM_WSS_SELECT_EVENT = 1; 
    ENM_WSS_TASK_FINISHED = 2;
    ENM_WSS_AWARD_FINISHED = 3;
}


enum EnmProgressValue
{
    ENM_PROGRESS_VALUE_0 = 0; 
    ENM_PROGRESS_VALUE_25 = 25; 
    ENM_PROGRESS_VALUE_50 = 50; 
    ENM_PROGRESS_VALUE_75 = 75; 
    ENM_PROGRESS_VALUE_100 = 100; 
}


enum EnmHouseState
{
    ENM_HOUSE_STATE_INVALID = 0; 
    ENM_HOUSE_STATE_PURCHASED = 1; 
    ENM_HOUSE_STATE_OPEN = 2; 
}


enum EnmGuideState
{
    ENM_GUIDE_STATE_INVALID = 0; 
    ENM_GUIDE_STATE_UNLOCK = 1; 
    ENM_GUIDE_STATE_READED = 2; 
}


enum EnmTmpTeamType
{
    ENM_TMP_TEAM_TYPE_NONE = 0; 
    ENM_TMP_TEAM_TYPE_TASK = 1; 
    ENM_TMP_TEAM_TYPE_DUNGEON = 2; 
    ENM_TMP_TEAM_TYPE_WANTED = 3; 
    ENM_TMP_TEAM_TYPE_MIND_PALACE = 4; 
    ENM_TMP_TEAM_TYPE_MAX = 5; 
}


enum EnmAwardShowType
{
    ENM_AST_NONE = 0; 
    ENM_AST_LEFT_DOWN = 1; 
    ENM_AST_MIDDLE = 2; 
    ENM_AST_SCREEN = 3; 
}
