<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Shared quotas and periodic resets.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\Lunaria.Common\Lunaria.Common.csproj" />
    <ProjectReference Include="..\Lunaria.Game.Resources\Lunaria.Game.Resources.csproj" />
    <ProjectReference Include="..\..\Protocol\Lunaria.Proto\Lunaria.Proto.csproj" />
  </ItemGroup>

</Project>
