// <auto-generated />
using System;
using Lunaria.Game.Player.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lunaria.Game.Player.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260907000000_AddRoleMotives")]
    partial class AddRoleMotives
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Lunaria.Game.Player.Persistence.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AccountKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("account_key");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_name");

                    b.Property<string>("ChannelUid")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_uid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Udid")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("udid");

                    b.Property<string>("Userid")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("AccountKey")
                        .IsUnique();

                    b.HasIndex("Userid")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Lunaria.Game.Player.Persistence.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gender");

                    b.Property<bool>("Initialized")
                        .HasColumnType("INTEGER")
                        .HasColumnName("initialized");

                    b.Property<long>("LastMintedInstId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_minted_inst_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT COLLATE NOCASE")
                        .HasColumnName("name");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("second_name");

                    b.Property<long>("Slot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("initialized = 1");

                    b.HasIndex("AccountId", "Slot")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Lunaria.Game.Player.Persistence.Entities.RoleCharacter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("BreakLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("break_level");

                    b.Property<uint>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("character_id");

                    b.Property<uint>("Exp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exp");

                    b.Property<long>("InstId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inst_id");

                    b.Property<uint>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<long>("MotiveUniqId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("motive_uniq_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId", "InstId")
                        .IsUnique();

                    b.ToTable("role_characters", (string)null);
                });

            modelBuilder.Entity("Lunaria.Game.Player.Persistence.Entities.RoleMotive", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("BreakLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("break_level");

                    b.Property<long>("ClaimTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("claim_time");

                    b.Property<long>("EquipedTarget")
                        .HasColumnType("INTEGER")
                        .HasColumnName("equiped_target");

                    b.Property<uint>("Exp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exp");

                    b.Property<uint>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<uint>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<bool>("Locked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("locked");

                    b.Property<uint>("MotiveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("motive_id");

                    b.Property<uint>("RefineLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("refine_level");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<long>("UniqId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uniq_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId", "UniqId")
                        .IsUnique();

                    b.ToTable("role_motives", (string)null);
                });

            modelBuilder.Entity("Lunaria.Game.Player.Persistence.Entities.RoleGuide", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<string>("Entries")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entries");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("RoleId");

                    b.ToTable("role_guides", (string)null);
                });

            modelBuilder.Entity("Lunaria.Game.Player.Persistence.Entities.RoleMail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("ExpireTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expire_time");

                    b.Property<bool>("HasAttach")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_attach");

                    b.Property<bool>("Important")
                        .HasColumnType("INTEGER")
                        .HasColumnName("important");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("items");

                    b.Property<long>("MailId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mail_id");

                    b.Property<bool>("Open")
                        .HasColumnType("INTEGER")
                        .HasColumnName("open");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<uint>("TemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("template_id");

                    b.Property<long>("Time")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time");

                    b.Property<uint>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId", "MailId")
                        .IsUnique();

                    b.ToTable("role_mails", (string)null);
                });

            modelBuilder.Entity("Lunaria.Game.Player.Persistence.Entities.RoleSave", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("RoleId");

                    b.ToTable("role_saves", (string)null);
                });

            modelBuilder.Entity("Lunaria.Game.Player.Persistence.Entities.Role", b =>
                {
                    b.HasOne("Lunaria.Game.Player.Persistence.Entities.Account", "Account")
                        .WithMany("Roles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Lunaria.Game.Player.Persistence.Entities.RoleCharacter", b =>
                {
                    b.HasOne("Lunaria.Game.Player.Persistence.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Lunaria.Game.Player.Persistence.Entities.RoleGuide", b =>
                {
                    b.HasOne("Lunaria.Game.Player.Persistence.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Lunaria.Game.Player.Persistence.Entities.RoleMotive", b =>
                {
                    b.HasOne("Lunaria.Game.Player.Persistence.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Lunaria.Game.Player.Persistence.Entities.RoleMail", b =>
                {
                    b.HasOne("Lunaria.Game.Player.Persistence.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Lunaria.Game.Player.Persistence.Entities.RoleSave", b =>
                {
                    b.HasOne("Lunaria.Game.Player.Persistence.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Lunaria.Game.Player.Persistence.Entities.Account", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
